version: "3.7"
services:
  rabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rabbitmq
    restart: always
    ports: 
      - 15672:15672
      - 5672:5672 
      - 1883:1883
      - 8883:8883
    hostname: stats
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: qupi
      RABBITMQ_DEFAULT_PASS: tutorial2020
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.5
    networks:
      rabbitmq_net:
        aliases: 
          - rabbitmq_host

volumes:
  data: {}
networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge
